Import('*')

sources = Split("""
    animation.cpp
    animation_action.cpp
    animation_cycle.cpp
    bone.cpp
    buffersource.cpp
    cal3d_wrapper.cpp
    coreanimation.cpp
    corebone.cpp
    corematerial.cpp
    coremesh.cpp
    coremodel.cpp
    coremorphanimation.cpp
    coreskeleton.cpp
    coresubmesh.cpp
    coresubmorphtarget.cpp
    dualquaternion.cpp
    error.cpp
    global.cpp
    hardwaremodel.cpp
    loader.cpp
    matrix.cpp
    mesh.cpp
    mixer.cpp
    model.cpp
    morphtargetmixer.cpp
    physique.cpp
    physiquedualquaternion.cpp
    platform.cpp
    quaternion.cpp
    renderer.cpp
    saver.cpp
    skeleton.cpp
    springsystem.cpp
    streamsource.cpp
    submesh.cpp
    tinyxml.cpp
    tinyxmlerror.cpp
    tinyxmlparser.cpp
    vector.cpp
""")

env = env.Copy()
env.Append(CPPPATH = ['..'])
env.Library('cal3d', sources)
env.SharedLibrary('cal3d', sources)
