#
# package name that must match the name used for the tarbal
#
PACKAGE=cal3d
#
# List of distributions for which package specifications are provided
#
DISTRIBUTIONS=unstable dapper fc4 fc5

LIBDIR ?= /usr/lib/packaging-farm

export INDEX_HTTP_SERVER=http://download.gna.org/cal3d
export INDEX_URL=

include ${LIBDIR}/Makefile
